CarInsuranceMVC/Controllers/HomeController.cs
using System.Web.Mvc;

namespace CarInsuranceMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return PartialView();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CarInsuranceMVC/Controllers/InsureeController.cs
using CarInsuranceMVC.Models;
using CarInsuranceMVC.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;

namespace CarInsuranceMVC.Controllers
{
    public class InsureeController : Controller
    {
        private InsuranceEntities db = new InsuranceEntities();

        // GET: Insuree
        public ActionResult Index()
        {
            return View(db.Insurees.ToList());
        }

        // GET: Insuree/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // GET: Insuree/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Insuree/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageType,QuoteMonthly,QuoteYearly")] Insuree insuree)
        {
            if (ModelState.IsValid)
            {
                db.Insurees.Add(insuree);
                db.SaveChanges();
                return RedirectToAction("QuoteCalculator");
            }

            return View(insuree);
        }

        // GET: Insuree/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // POST: Insuree/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FirstName,LastName,EmailAddress,DateOfBirth,CarYear,CarMake,CarModel,DUI,SpeedingTickets,CoverageType,QuoteMonthly,QuoteYearly")] Insuree insuree)
        {
            if (ModelState.IsValid)
            {
                db.Entry(insuree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(insuree);
        }

        // GET: Insuree/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Insuree insuree = db.Insurees.Find(id);
            if (insuree == null)
            {
                return HttpNotFound();
            }
            return View(insuree);
        }

        // POST: Insuree/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Insuree insuree = db.Insurees.Find(id);
            db.Insurees.Remove(insuree);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }



        public ActionResult QuoteCalculator()
        {

            using (InsuranceEntities db = new InsuranceEntities())
            {
                var insurees = db.Insurees;
                var autoQuotes = db.AutoQuotes;

                var autoQuoteVMs = new List<AutoQuoteVM>();
                var insureeVMs = new List<InsureeVM>();

                {
                    foreach (Insuree insuree in insurees)
                    {

                        var autoQuote = new AutoQuote();
                        var autoQuoteVM = new AutoQuoteVM();
                        var insureeVM = new InsureeVM();


                        var baseRate = 50.00;


                        var age = DateTime.Now.Year - insuree.DateOfBirth.Year;



                        if (insuree.DateOfBirth.Month > DateTime.Now.Month
                         || insuree.DateOfBirth.Month == DateTime.Now.Month
                          && insuree.DateOfBirth.Day > DateTime.Now.Day)
                            age--;

                        var insureeAge = Convert.ToInt32(age);


                        double under18 = (insureeAge < 18) ? 100.00 : 0.00;
                        double btw19and25 = ((insureeAge > 18) && (age <= 25)) ? 50.00 : 0.00;
                        double over25 = (insureeAge > 25) ? 25.00 : 0.00;


                        double autoYearPrior2000 = (insuree.CarYear < 2000) ? 25.00 : 0.00;
                        double autoYearAfter2015 = (insuree.CarYear > 2015) ? 25.00 : 0.00;


                        double yesIsPorsche = (insuree.CarMake == "Porsche") ? 25.00 : 0.00;
                        double yesIsCarrera = (insuree.CarModel == "Carrera") ? 25.00 : 0.00;

                        double subtotalBeforeDUI = baseRate + under18 + btw19and25 + over25 +
                                                   autoYearPrior2000 + autoYearAfter2015 + yesIsPorsche +
                                                   yesIsCarrera;

                        int isTrueDUI = (insuree.DUI == true) ? 1 : 0;
                        double yesDUI = subtotalBeforeDUI * 0.25;//Calculating the rate of increase if DUI is true
                        double duiRate = (isTrueDUI == 1) ? yesDUI : 0.00;// value that will be placed in Quote DUIRateUP25Percent
                        double subtotalAfterDUI = duiRate + subtotalBeforeDUI;// value that will be placed in Quote SubTotalAfterDUICalc

                        int speedingTickets = insuree.SpeedingTickets;
                        double speedingTicketsRate = speedingTickets * 10.00;

                        double subtotalBeforeCoverageCalc = subtotalAfterDUI + speedingTicketsRate;
                        int coverageTypeFull = (insuree.CoverageType == true) ? 1 : 0;
                        double fullCoverageRate = subtotalBeforeCoverageCalc * 0.50;// calculating the rate of increase if FullCoverage is true
                        double yesFullCoverage = (coverageTypeFull == 1) ? fullCoverageRate : 0.00;//value that will be placed in FullCovRateUP50Percent  
                        double subtotalAfterCoverageCalc = subtotalBeforeCoverageCalc + yesFullCoverage;



                        double monthlyQuote = subtotalAfterCoverageCalc;
                        double yearlyQuote = subtotalAfterCoverageCalc * 12;

                        insuree.QuoteMonthly = Convert.ToDecimal(monthlyQuote);
                        insuree.QuoteYearly = Convert.ToDecimal(yearlyQuote);
                        autoQuote.InsureeId = Convert.ToInt32(insuree.Id);
                        autoQuote.BaseRate = Convert.ToDecimal(baseRate);
                        autoQuote.AgeUnder18 = Convert.ToDecimal(under18);
                        autoQuote.AgeBtw19and25 = Convert.ToDecimal(btw19and25);
                        autoQuote.Age26andUp = Convert.ToDecimal(over25);
                        autoQuote.AutoYearBefore2000 = Convert.ToDecimal(autoYearPrior2000);
                        autoQuote.AutoYearAfter2015 = Convert.ToDecimal(autoYearAfter2015);
                        autoQuote.IsPorsche = Convert.ToDecimal(yesIsPorsche);
                        autoQuote.IsCarrera = Convert.ToDecimal(yesIsCarrera);
                        autoQuote.SubTotalBeforeDuiCalc = Convert.ToDecimal(subtotalBeforeDUI);
                        autoQuote.DuiRateUp25Percent = Convert.ToDecimal(duiRate);
                        autoQuote.SubTotalAfterDuiCalc = Convert.ToDecimal(subtotalAfterDUI);
                        autoQuote.SpeedingTickets = Convert.ToDecimal(speedingTicketsRate);
                        autoQuote.SubTotalBeforeCoverageCalc = Convert.ToDecimal(subtotalBeforeCoverageCalc);
                        autoQuote.FullCoverageRateUp50Percent = Convert.ToDecimal(fullCoverageRate);
                        autoQuote.SubTotalAfterCoverageCalc = Convert.ToDecimal(subtotalAfterCoverageCalc);


                        insureeVM.QuoteMonthly = insuree.QuoteMonthly;
                        insureeVM.QuoteYearly = insuree.QuoteYearly;
                        autoQuoteVM.InsureeId = autoQuote.InsureeId;
                        autoQuoteVM.BaseRate = autoQuote.BaseRate;
                        autoQuoteVM.AgeUnder18 = autoQuote.AgeUnder18;
                        autoQuoteVM.AgeBtw19and25 = autoQuote.AgeBtw19and25;
                        autoQuoteVM.Age26andUp = autoQuote.Age26andUp;
                        autoQuoteVM.AutoYearBefore2000 = autoQuote.AutoYearBefore2000;
                        autoQuoteVM.AutoYearAfter2015 = autoQuote.AutoYearAfter2015;
                        autoQuoteVM.IsPorsche = autoQuote.IsPorsche;
                        autoQuoteVM.IsCarrera = autoQuote.IsCarrera;
                        autoQuoteVM.SubTotalBeforeDuiCalc = autoQuote.SubTotalBeforeDuiCalc;
                        autoQuoteVM.DuiRateUp25Percent = autoQuote.DuiRateUp25Percent;
                        autoQuoteVM.SubTotalAfterDuiCalc = autoQuote.SubTotalAfterDuiCalc;
                        autoQuoteVM.SpeedingTickets = autoQuote.SpeedingTickets;

CarInsuranceMVC/Views/Home/About.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="~/Content/HomeAboutPageStyles.css"/>
</head>
<body id="HomeAboutPageBodyContainer">

  <div id="HomeAboutBackground">
    <img src="~/Content/Images/SeasideDrive.jpg" alt="Seaside Road Trip" />
  </div>
  <div id="ColorOverlay">
    <div id="ImageTextOverlay">
      <div class="jumbotron">

        <h1 id="BetterDeal"style="font-size:4em;">Can you get a better deal on your auto insurance?</h1>

        <h3 id="Yes">The answer is "YES"! Absolutely!</h3><br /><br />
        <h2 id="RightPlace">
          ... you've definitely come to the right place!
        </h2><br />

        <h1 id="CompanyName">The Auto Insurance Connection</h1>
        
        <div id="SalesPitch">
           <h3>Our Mission</h3>
            <p>To Deliver Exceptional Coverage and Provide Outstanding Service at The Best Price Ever!!!
           <h3>The Process:</h3>
            <p>
              &#64 The Auto Insurance Connection, every policy is a precisely crafted and highly customized using our<br/> patented formula which evaluates Three Key Factors:
              Lifestyle, Personal Finance/Budget, and Coverage Requirements.
            </p>
           <h3>The Result:</h3>
            <p>A top-notch Auto Inurance Solution that is custom-made and tailor-fit just for you!</p>
          <br /><br />
          <p>Life is like a Road Trip... everyone's experience is unique and so are their insurance needs!<br />So, take a minute and do yourself a favor...</p>
            <h3 id="Join"> Join US! and Let The Good Times Roll...</h3>
          <div id="FreeQuoteButton" >
  @Html.ActionLink("Get Your Free Quote Today!", "Create", "Insuree", new { @class = "font-size:1.75em; color:white;" })
</div>
        </div>
  </div>
</div>
    </div>
</body>
</html>

CarInsuranceMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

CarInsuranceMVC/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Josefin+Sans:ital,wght@0,100;0,200;0,300;0,400;1,100;1,200;1,300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="~/Content/HomeIndexLandingPageStyles.css" />
</head>
<body id="HomeIndexLandingPageBodyContainer">

  <div id="HomeIndexBackground">
    <img src="~/Content/Images/FrontPage.jpg" alt="Driving Down The Road Photo" />
  </div>
  <div id="ColorOverlay">
    <div id="ImageTextOverlay">
      <div class="jumbotron">

        <h1 style="font-size:5em;">Are you paying too much for auto insurance?</h1>

        <h3 id="Sadly">Sadly, the answer is probably "YES".</h3><br /><br />
        <h2 id="RightPlace">
          Well,... you've come to the right place!
        </h2><br /><br /><br /><br>
       <p id="NoHassles"> No Hassles. No Gimmicks. No Pressure. No Surprises,...<br/>and No Hidden Fees.<br /><br/> So, just take a moment and do yourself a favor...<br/>
        <span> Join US! and Let The Good Times Roll...</span>
      </p>
        <div id="FreeQuoteButton" class=" btn btn-outline-primary">
          @Html.ActionLink("GET A FREE QUOTE NOW!", "Create", "Insuree", new { @class = "btn btn-large" })
        </div>
        


      </div>
    </div>
  </div>

</body>
</html>